%YAML:1.0
#kinematic constrain
extrinsicR: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ -0.834505  ,  0.550634 ,-0.00549067,
                   -0.550661,   -0.834454,  0.00919684,
                     0.000481873,   0.0107003 ,   0.999943]
#Translation from camera frame to imu frame, imu^T_cam
extrinsicT: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [4.84219, 1.0575,-0.563387]

Xoi: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [0.0,0.0,1.5]

Xoj: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [0.0,0.0,-1.5]
center_topic: "/mavros/imu/data_raw"
agent1_topic: "/"
agent2_topic: "/"

output_name: "/home/mao/catkin_ws/src/VINS-Mono-master/offline_process/config/i.csv"
output_name_j: "/home/mao/catkin_ws/src/VINS-Mono-master/offline_process/config/j.csv"
tr_flag: 1
e2_flag: 0
Number: 20000  #优化次数越小，精度越高
seq_n: 2 #临边数量为seq_n-1
Fre: 100 # when set to 0 means using number

data_noise: 0 # 1: using data_noise.csv
w_p: 1 #sequnce edge p
w_q: 1  #sequnce edge q
w_v: 1 #sequnce edge v
w_k_p: 1 #kinematic p weight
w_k_v: 1 #kinematic v weight
align:  0
propagate: 0
processnumber: -1 #stop iteration
max_iteration_number: 20
all_process: 1 #optimization all
if_lossfunction: 0
if_xoi: 0 #estimate delta_xoi

binary_path: 1    #optimize two path
