%YAML:1.0

#common parameters
imu_topic: "/mavros/imu/data_raw"
image_topic: "/zed/zed_node/left/image_rect_gray"
output_path: "/home/mao/output/pose_graph/"

#camera calibration 
model_type: PINHOLE
camera_name: camera
image_width: 672
image_height: 376
distortion_parameters:
   k1: 0
   k2: 0
   p1: 0
   p2: 0
projection_parameters:
   fx: 437.8865561639657
   fy: 441.50728406651365
   cx: 177.21932443006378
   cy: 169.5205

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning.                        
#If you choose 0 or 1, you should write down the following matrix.
#Rotation from camera frame to imu frame, imu^R_cam
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.12671903, -0.00069244,  0.99193841,
           -0.99166901,  0.02322668,  0.12670083, 
           -0.02312717, -0.99972998,  0.00225659]
#Translation from camera frame to imu frame, imu^T_cam
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [-0.04855509,0.0554196, -0.14746982]
   
#kinematic constrain
extrinsicR: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ -9.35782592e-01, -3.52172047e-01, 1.69053000e-02,
            3.52226567e-01, -9.35914726e-01, 2.65285569e-04,
            1.57284930e-02, 6.20274539e-03, 9.99857060e-01]
#Translation from camera frame to imu frame, imu^T_cam
extrinsicT: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [4.49447784, -1.61980881, 0.9375474]

Xoi: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [0.0,0.0,1.5]

kinematic_constrain: 0
output_name: "vins_agent2.csv"
#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 1             # if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.140739989705           # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.0192060643182         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.000479901028407        # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 0.000152503659655       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.81007     # gravity magnitude

#loop closure parameters
loop_closure: 0                  # start loop closure
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
fast_relocalization: 0             # useful in real-time and large project
pose_graph_save_path: "/home/mao/output/pose_graph/" # save and load path

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.0025317783192816733                           # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#rolling shutter parameters
rolling_shutter: 0                  # 0: global shutter camera, 1: rolling shutter camera
rolling_shutter_tr: 0               # unit: s. rolling shutter read out time per frame (from data sheet). 

#visualization parameters
save_image: 0                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
visualize_imu_forward: 0        # output imu forward propogation to achieve low latency and high frequence results
visualize_camera_size: 0.4      # size of camera marker in RVIZ
